default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: sqlite3
  database: db/database.db

test:
  adapter: sqlite3
  database: db/database.db

production:
  adapter: postgresql
  database: database #rename this to whatever you want

